### ISSUE TITLE
ChannelNameTooLongException

### ISSUE THREAD

**Issue by Carlosgrr** [egg82/TrollCommandsPlusPlus#11]
My server is trolling me xD

It is giving me the ChannelNameTooLong Exception, see it below

------------------------------------------

java.lang.RuntimeException: Cannot create channel.
    at me.egg82.tcpp.lib.ninja.egg82.bukkit.messaging.EnhancedBungeeMessageHandler.createChannel(EnhancedBungeeMessageHandler.java:107) ~[?:?]
    at me.egg82.tcpp.Loaders.loadMessaging(Loaders.java:81) ~[?:?]
    at me.egg82.tcpp.TrollCommandsPlusPlus.onEnable(TrollCommandsPlusPlus.java:172) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot%20latest:git-Spigot-2086bb0-8cc5a7e]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot%20latest:git-Spigot-2086bb0-8cc5a7e]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot%20latest:git-Spigot-2086bb0-8cc5a7e]
    at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot%20latest:git-Spigot-2086bb0-8cc5a7e]
    at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot%20latest:git-Spigot-2086bb0-8cc5a7e]
    at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot%20latest:git-Spigot-2086bb0-8cc5a7e]
    at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot%20latest:git-Spigot-2086bb0-8cc5a7e]
    at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot%20latest:git-Spigot-2086bb0-8cc5a7e]
    at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot%20latest:git-Spigot-2086bb0-8cc5a7e]
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot%20latest:git-Spigot-2086bb0-8cc5a7e]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: org.bukkit.plugin.messaging.ChannelNameTooLongException: Attempted to send a Plugin Message to a channel that was too large. The maximum length a channel may be is 20 chars (attempted 27 - 'trollcommandsplusplus:troll.
    at org.bukkit.plugin.messaging.StandardMessenger.validateChannel(StandardMessenger.java:446) ~[spigot%20latest:git-Spigot-2086bb0-8cc5a7e]
    at org.bukkit.plugin.messaging.StandardMessenger.registerIncomingPluginChannel(StandardMessenger.java:208) ~[spigot%20latest:git-Spigot-2086bb0-8cc5a7e]
    at me.egg82.tcpp.lib.ninja.egg82.bukkit.messaging.EnhancedBungeeMessageHandler.createChannel(EnhancedBungeeMessageHandler.java:98) ~[?:?]
    ... 13 more

**Comment by egg82** [comment]
TC++ is currently in the middle of an update to 1.14, which should eliminate bugs such as this. It will be resolved soon!
