### ISSUE TITLE
Plugin just doesn't load

### ISSUE THREAD

**Issue by ItsAlpal** [egg82/TrollCommandsPlusPlus#5]
@egg82 
A few months ago, I had this plugin and it worked perfectly. I recently re-installed it and whenever i try to load the plugin in ANY way (/reload, restart server, plugman) it just spits out an error in the console and disables itself. Here is the error on startup:
`[18:53:41 ERROR]: Error occurred while enabling TrollCommandsPlusPlus v6.28.53 (Is it up to date?)
java.lang.NoSuchMethodError: com.google.common.collect.Sets$SetView.iterator()Lcom/google/common/collect/UnmodifiableIterator;
        at org.reflections.Reflections.expandSuperTypes(Reflections.java:380) ~[?:?]
        at org.reflections.Reflections.<init>(Reflections.java:126) ~[?:?]
        at me.egg82.tcpp.lib.ninja.egg82.utils.ReflectUtil.getClasses(ReflectUtil.java:206) ~[?:?]
        at me.egg82.tcpp.lib.ninja.egg82.plugin.handlers.EventListener.<init>(EventListener.java:38) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_162]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_162]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_162]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_162]
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_162]
        at me.egg82.tcpp.lib.ninja.egg82.patterns.ServiceLocator.initializeService(ServiceLocator.java:136) ~[?:?]
        at me.egg82.tcpp.lib.ninja.egg82.patterns.ServiceLocator.provideService(ServiceLocator.java:73) ~[?:?]
        at me.egg82.tcpp.lib.ninja.egg82.plugin.BasePlugin.onEnable(BasePlugin.java:117) ~[?:?]
        at me.egg82.tcpp.TrollCommandsPlusPlus.onEnable(TrollCommandsPlusPlus.java:178) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_162]`
Also note i've tried removing ALL other plugins except TCPP and still no result.
And i've attached a screenshot of /plugins.
Please get back to me when u can.

![capture](https://user-images.githubusercontent.com/27193116/38865676-19151c40-4271-11e8-9341-6f4ce9bcf093.PNG)

Server version: 1.11.2 (viaversion, viabackwards, viarewind)
EDIT: ik im using punishmental, but i srsly want this plugin because i think its much much better and more feature-rich

**Comment by ItsAlpal** [comment]
Just a quick update. I tried putting tcpp on a 1.12.2 server and it worked fine. But I still need it to work on 1.11.2.

EDIT: im in australia. cant get back to u until tomorrow (~9:00am AWST - 8pm CST)

**Comment by ItsAlpal** [comment]
Consider this a bug report. Just moved to previous version (5.27.52) and everything works fine.

Closing.

**Comment by egg82** [comment]
Thanks for the report! I've been busy recently but I'll look into the exception.

It seems I'm (for whatever reason) using "org.reflections" instead of the internal Reflection library I shaded into that jar. Since that library is dependent on the server implementation it can sometimes cause exceptions like that on older MC versions.

Also please be aware /reload isn't officially supported and can cause a ton of issues with many plugins. It should work just fine with TC++, but you never know.

**Comment by ItsAlpal** [comment]
@egg82 soo... what are you saying? is this your error or did i do something wrong?
