### ISSUE TITLE
Plugin Conflict

### ISSUE THREAD

**Issue by KohGeek** [egg82/TrollCommandsPlusPlus#6]
TrollCommands++ 6.28.53 seems to have issue loading when I have both LandLords and ViaVersion installed.

I'm running on Windows 10, and unknown Linux Host, running on Java 8 1.8.171, running on Spigot-1.12.2.

[LandLords 2 b162](https://www.spigotmc.org/resources/beta-landlord-2.44398/)
[ViaVersion 1.3.0](https://www.spigotmc.org/resources/viaversion.19254/)

Links to related issues on respective plugins:
[ViaVersion Issues](https://github.com/MylesIsCool/ViaVersion/issues/825)
[LandLord Issues](https://github.com/SpatiumPrinceps/LandLord/issues/75)

The result of testing:
1) LandLords and ViaVersion installed: TC++ crashes on load.
2) LandLords only installed: TC++ loads, but LandLords crashes.
3) ViaVersion only installed: TC++ loads normally.

Crash log of 1st testing:
```
[00:00:38 ERROR]: org.reflections.util.ConfigurationBuilder.filterInputsBy(Lcom/google/common/base/Predicate;)Lorg/reflections/util/ConfigurationBuilder; initializing TrollCommandsPlusPlus v6.28.53 (Is it up to date?)
java.lang.NoSuchMethodError: org.reflections.util.ConfigurationBuilder.filterInputsBy(Lcom/google/common/base/Predicate;)Lorg/reflections/util/ConfigurationBuilder;
        at me.egg82.tcpp.lib.ninja.egg82.utils.ReflectUtil.getClasses(ReflectUtil.java:203) ~[?:?]
        at me.egg82.tcpp.lib.ninja.egg82.plugin.utils.VersionUtil.getBestMatch(VersionUtil.java:49) ~[?:?]
        at me.egg82.tcpp.lib.ninja.egg82.plugin.BasePlugin.reflect(BasePlugin.java:181) ~[?:?]
        at me.egg82.tcpp.lib.ninja.egg82.plugin.BasePlugin.reflect(BasePlugin.java:178) ~[?:?]
        at me.egg82.tcpp.lib.ninja.egg82.plugin.BasePlugin.onLoad(BasePlugin.java:90) ~[?:?]
        at me.egg82.tcpp.TrollCommandsPlusPlus.onLoad(TrollCommandsPlusPlus.java:117) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:310) [spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
```

Continued crash log, further down the one above of 1st testing:
```
[00:01:08 ERROR]: Error occurred while enabling TrollCommandsPlusPlus v6.28.53 (Is it up to date?)
java.lang.NoSuchMethodError: org.reflections.util.ConfigurationBuilder.filterInputsBy(Lcom/google/common/base/Predicate;)Lorg/reflections/util/ConfigurationBuilder;
        at me.egg82.tcpp.lib.ninja.egg82.utils.ReflectUtil.getClasses(ReflectUtil.java:203) ~[?:?]
        at me.egg82.tcpp.lib.ninja.egg82.plugin.handlers.EventListener.<init>(EventListener.java:38) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_171]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_171]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_171]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_171]
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_171]
        at me.egg82.tcpp.lib.ninja.egg82.patterns.ServiceLocator.initializeService(ServiceLocator.java:136) ~[?:?]
        at me.egg82.tcpp.lib.ninja.egg82.patterns.ServiceLocator.provideService(ServiceLocator.java:73) ~[?:?]
        at me.egg82.tcpp.lib.ninja.egg82.plugin.BasePlugin.onEnable(BasePlugin.java:117) ~[?:?]
        at me.egg82.tcpp.TrollCommandsPlusPlus.onEnable(TrollCommandsPlusPlus.java:178) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
```

Crash Log of 2nd testing:
```
[00:03:58 ERROR]: Error occurred while enabling Landlord v1.162 (Is it up to date?)
java.lang.NoSuchMethodError: org.reflections.ReflectionUtils.withAnnotation(Ljava/lang/Class;)Lshaded/com/google/common/base/Predicate;
        at biz.princeps.lib.storage.DatabaseAPI.saveObject(DatabaseAPI.java:159) ~[?:?]
        at biz.princeps.landlord.Landlord.handleDatabase(Landlord.java:204) ~[?:?]
        at biz.princeps.landlord.Landlord.onEnable(Landlord.java:111) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-eadd615-4509a14]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
```

**Comment by gw2princeps** [comment]
Can be closed, was an error on my side. TrollCommands does load now, atleast on my machine xD

**Comment by KohGeek** [comment]
Seems all 3 of you guys are very attentive and fixes bug very quickly, kudos! When will the next version that fixes this be released?

Just realised you're the LandLord dev >,>. Closing.

**Comment by egg82** [comment]
Apologies for not being super active; haven't had much time to spend on my plugins recently. I'll have some time again in a few days for an update.

Reflections (org.reflections) HATES being relocated, at least from my tests. Unfortunately that forced me to put it into the global namespace, which can cause incompatibility issues when other plugins are also shading that library into the main namespace but use outdated versions. This can also cause issues with Spigot/Paper itself since it's included in the main jars, but I try to keep up with the versions pre-installed on those.
