### ISSUE TITLE
Spams console when SourceForge is down

### ISSUE THREAD

**Issue by raku-cat** [egg82/TrollCommandsPlusPlus#8]
I checked on my server earlier to be greeted with tons of lines from TCPP about an http error

```
[22:59:52] [TrollCommandsPlusPlus-scheduled-0/WARN]: java.io.IOException: Server returned HTTP response code: 503 for URL: http://opennlp.sourceforge.net/models-1.5/en-pos-maxent.bin
[22:59:52] [TrollCommandsPlusPlus-scheduled-0/WARN]:    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
[22:59:52] [TrollCommandsPlusPlus-scheduled-0/WARN]:    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
[22:59:52] [TrollCommandsPlusPlus-scheduled-0/WARN]:    at java.net.URL.openStream(URL.java:1045)
[22:59:52] [TrollCommandsPlusPlus-scheduled-0/WARN]:    at me.egg82.tcpp.extern.opennlp.tools.util.model.BaseModel.<init>(BaseModel.java:190)
[22:59:52] [TrollCommandsPlusPlus-scheduled-0/WARN]:    at me.egg82.tcpp.extern.opennlp.tools.postag.POSModel.<init>(POSModel.java:109)
[22:59:52] [TrollCommandsPlusPlus-scheduled-0/WARN]:    at me.egg82.tcpp.TrollCommandsPlusPlus.getTagger(TrollCommandsPlusPlus.java:355)
[22:59:52] [TrollCommandsPlusPlus-scheduled-0/WARN]:    at me.egg82.tcpp.TrollCommandsPlusPlus.access$8(TrollCommandsPlusPlus.java:353)
[22:59:52] [TrollCommandsPlusPlus-scheduled-0/WARN]:    at me.egg82.tcpp.TrollCommandsPlusPlus$5.run(TrollCommandsPlusPlus.java:368)
[22:59:52] [TrollCommandsPlusPlus-scheduled-0/WARN]:    at me.egg82.tcpp.lib.ninja.egg82.utils.ThreadUtil$2.run(ThreadUtil.java:70)
[22:59:52] [TrollCommandsPlusPlus-scheduled-0/WARN]:    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[22:59:52] [TrollCommandsPlusPlus-scheduled-0/WARN]:    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[22:59:52] [TrollCommandsPlusPlus-scheduled-0/WARN]:    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
[22:59:52] [TrollCommandsPlusPlus-scheduled-0/WARN]:    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
[22:59:52] [TrollCommandsPlusPlus-scheduled-0/WARN]:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[22:59:52] [TrollCommandsPlusPlus-scheduled-0/WARN]:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[22:59:52] [TrollCommandsPlusPlus-scheduled-0/WARN]:    at java.lang.Thread.run(Thread.java:748)
[22:59:52] [TrollCommandsPlusPlus-scheduled-0/WARN]: java.io.IOException: Server returned HTTP response code: 503 for URL: http://opennlp.sourceforge.net/models-1.5/en-pos-perceptron.bin
[22:59:52] [TrollCommandsPlusPlus-scheduled-0/WARN]:    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
[22:59:52] [TrollCommandsPlusPlus-scheduled-0/WARN]:    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
[22:59:52] [TrollCommandsPlusPlus-scheduled-0/WARN]:    at java.net.URL.openStream(URL.java:1045)
[22:59:52] [TrollCommandsPlusPlus-scheduled-0/WARN]:    at me.egg82.tcpp.extern.opennlp.tools.util.model.BaseModel.<init>(BaseModel.java:190)
[22:59:52] [TrollCommandsPlusPlus-scheduled-0/WARN]:    at me.egg82.tcpp.extern.opennlp.tools.postag.POSModel.<init>(POSModel.java:109)
[22:59:52] [TrollCommandsPlusPlus-scheduled-0/WARN]:    at me.egg82.tcpp.TrollCommandsPlusPlus.getTagger(TrollCommandsPlusPlus.java:361)
[22:59:52] [TrollCommandsPlusPlus-scheduled-0/WARN]:    at me.egg82.tcpp.TrollCommandsPlusPlus.access$8(TrollCommandsPlusPlus.java:353)
[22:59:52] [TrollCommandsPlusPlus-scheduled-0/WARN]:    at me.egg82.tcpp.TrollCommandsPlusPlus$5.run(TrollCommandsPlusPlus.java:368)
[22:59:52] [TrollCommandsPlusPlus-scheduled-0/WARN]:    at me.egg82.tcpp.lib.ninja.egg82.utils.ThreadUtil$2.run(ThreadUtil.java:70)
[22:59:52] [TrollCommandsPlusPlus-scheduled-0/WARN]:    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[22:59:52] [TrollCommandsPlusPlus-scheduled-0/WARN]:    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[22:59:52] [TrollCommandsPlusPlus-scheduled-0/WARN]:    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
[22:59:52] [TrollCommandsPlusPlus-scheduled-0/WARN]:    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
[22:59:52] [TrollCommandsPlusPlus-scheduled-0/WARN]:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[22:59:52] [TrollCommandsPlusPlus-scheduled-0/WARN]:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[22:59:52] [TrollCommandsPlusPlus-scheduled-0/WARN]:    at java.lang.Thread.run(Thread.java:748)
[23:00:03] [TrollCommandsPlusPlus-scheduled-1/WARN]: java.io.IOException: Server returned HTTP response code: 503 for URL: http://opennlp.sourceforge.net/models-1.5/en-pos-maxent.bin
[23:00:03] [TrollCommandsPlusPlus-scheduled-1/WARN]:    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
[23:00:03] [TrollCommandsPlusPlus-scheduled-1/WARN]:    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
[23:00:03] [TrollCommandsPlusPlus-scheduled-1/WARN]:    at java.net.URL.openStream(URL.java:1045)
[23:00:03] [TrollCommandsPlusPlus-scheduled-1/WARN]:    at me.egg82.tcpp.extern.opennlp.tools.util.model.BaseModel.<init>(BaseModel.java:190)
[23:00:03] [TrollCommandsPlusPlus-scheduled-1/WARN]:    at me.egg82.tcpp.extern.opennlp.tools.postag.POSModel.<init>(POSModel.java:109)
[23:00:03] [TrollCommandsPlusPlus-scheduled-1/WARN]:    at me.egg82.tcpp.TrollCommandsPlusPlus.getTagger(TrollCommandsPlusPlus.java:355)
[23:00:03] [TrollCommandsPlusPlus-scheduled-1/WARN]:    at me.egg82.tcpp.TrollCommandsPlusPlus.access$8(TrollCommandsPlusPlus.java:353)
[23:00:03] [TrollCommandsPlusPlus-scheduled-1/WARN]:    at me.egg82.tcpp.TrollCommandsPlusPlus$5.run(TrollCommandsPlusPlus.java:368)
[23:00:03] [TrollCommandsPlusPlus-scheduled-1/WARN]:    at me.egg82.tcpp.lib.ninja.egg82.utils.ThreadUtil$2.run(ThreadUtil.java:70)
[23:00:03] [TrollCommandsPlusPlus-scheduled-1/WARN]:    at me.egg82.tcpp.lib.ninja.egg82.core.MinMaxScheduledThreadPoolExecutor$2.run(MinMaxScheduledThreadPoolExecutor.java:606)
[23:00:03] [TrollCommandsPlusPlus-scheduled-1/WARN]:    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[23:00:03] [TrollCommandsPlusPlus-scheduled-1/WARN]:    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[23:00:03] [TrollCommandsPlusPlus-scheduled-1/WARN]:    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
[23:00:03] [TrollCommandsPlusPlus-scheduled-1/WARN]:    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
[23:00:03] [TrollCommandsPlusPlus-scheduled-1/WARN]:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[23:00:03] [TrollCommandsPlusPlus-scheduled-1/WARN]:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[23:00:03] [TrollCommandsPlusPlus-scheduled-1/WARN]:    at java.lang.Thread.run(Thread.java:748)
[23:00:03] [TrollCommandsPlusPlus-scheduled-1/WARN]: java.io.IOException: Server returned HTTP response code: 503 for URL: http://opennlp.sourceforge.net/models-1.5/en-pos-perceptron.bin
[23:00:03] [TrollCommandsPlusPlus-scheduled-1/WARN]:    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
[23:00:03] [TrollCommandsPlusPlus-scheduled-1/WARN]:    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
[23:00:03] [TrollCommandsPlusPlus-scheduled-1/WARN]:    at java.net.URL.openStream(URL.java:1045)
[23:00:03] [TrollCommandsPlusPlus-scheduled-1/WARN]:    at me.egg82.tcpp.extern.opennlp.tools.util.model.BaseModel.<init>(BaseModel.java:190)
[23:00:03] [TrollCommandsPlusPlus-scheduled-1/WARN]:    at me.egg82.tcpp.extern.opennlp.tools.postag.POSModel.<init>(POSModel.java:109)
[23:00:03] [TrollCommandsPlusPlus-scheduled-1/WARN]:    at me.egg82.tcpp.TrollCommandsPlusPlus.getTagger(TrollCommandsPlusPlus.java:361)
[23:00:03] [TrollCommandsPlusPlus-scheduled-1/WARN]:    at me.egg82.tcpp.TrollCommandsPlusPlus.access$8(TrollCommandsPlusPlus.java:353)
[23:00:03] [TrollCommandsPlusPlus-scheduled-1/WARN]:    at me.egg82.tcpp.TrollCommandsPlusPlus$5.run(TrollCommandsPlusPlus.java:368)
[23:00:03] [TrollCommandsPlusPlus-scheduled-1/WARN]:    at me.egg82.tcpp.lib.ninja.egg82.utils.ThreadUtil$2.run(ThreadUtil.java:70)
[23:00:03] [TrollCommandsPlusPlus-scheduled-1/WARN]:    at me.egg82.tcpp.lib.ninja.egg82.core.MinMaxScheduledThreadPoolExecutor$2.run(MinMaxScheduledThreadPoolExecutor.java:606)
[23:00:03] [TrollCommandsPlusPlus-scheduled-1/WARN]:    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
```
I haven't inspected anything to see how fundamental this file is for functioning, but that being the case I think the behavior should be to warn with that error once and then disable the plugin.

**Comment by egg82** [comment]
I noticed this as well on my error reporting service. ebe671f should (mostly) fix it.
